import 'package:get/get.dart';

class DialogsTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'enter': 'Enter',
      'password': 'Pass',
      'login': 'Login',
      'login_error' : 'The field cannot be empty',
      'oops' : 'Oops...',
      'no_internet' : 'Something wrong with your\nconnection, please try again.',
      'retry' : 'Retry',
      'dd' : 'd.',
      'hh' : 'h.',
      'mm' : 'min.',
      'wastedAllTime' : 'Wasted time',
      'wastedTime' : 'Time',
      'clients' : 'Clients',
      'taskList' : 'To-do list',
      'tasksAll' : 'Tasks',
      'no_tasks' : 'No tasks!',
      'new_task' : 'New task',
      'status' : 'Status',
      'status_done' : 'Done',
      'status_canceled' : 'Canceled',
      'status_postponed' : 'Postponed',
      'status_testing' : 'Testing',
      'status_developing' : 'Developing',
      'comment' : 'Comment',
      'ok' : 'Ok',
    },
    'ru_UA': {
      'enter': 'Вход',
      'password': 'Пароль',
      'login': 'Логин',
      'login_error' : 'Поле не может быть пустым',
      'oops' : 'Упс...',
      'no_internet' : 'Отсутствует соединение c\nинтернетом, попробуйте ещё раз.',
      'retry' : 'Повторить',
      'dd' : 'д.',
      'hh' : 'ч.',
      'mm' : 'мин.',
      'wastedAllTime' : 'Общее время',
      'wastedTime' : 'Время',
      'clients' : 'Клиенты',
      'taskList' : 'Список задач',
      'tasksAll' : 'Задач',
      'no_tasks' : 'Задач ещё нет!',
      'new_task' : 'Новая задача',
      'status' : 'Статус',
      'status_done' : 'Выполнено',
      'status_canceled' : 'Отменено',
      'status_postponed' : 'Отложено',
      'status_testing' : 'Тестируется',
      'status_developing' : 'В разработке',
      'comment' : 'Комментарий',
      'ok' : 'Ок',
    },
    'uk_UA': {
      'enter': 'Вхід',
      'password': 'Пароль',
      'login': 'Логін',
      'login_error' : 'Поле не може бути пустим',
      'oops' : 'Упс...',
      'no_internet' : 'Відсутній зв\'язок з мережею\nінтернет, спробуйте ще раз.',
      'retry' : 'Повторити',
      'dd' : 'д.',
      'hh' : 'г.',
      'mm' : 'хв.',
      'wastedAllTime' : 'Загальний час',
      'wastedTime' : 'Час',
      'clients' : 'Кліенти',
      'taskList' : 'Перелік завдань',
      'tasksAll' : 'Завдань',
      'no_tasks' : 'Завдань ще нема!',
      'new_task' : 'Нове завдання',
      'status' : 'Статус',
      'status_done' : 'Виконано',
      'status_canceled' : 'Відмінено',
      'status_postponed' : 'Відкалено',
      'status_testing' : 'Тестується',
      'status_developing' : 'В розробці',
      'comment' : 'Комментар',
      'ok' : 'Ок',
    },
  };
}